version: "3.8"
services:
  backend:
    build: ./vidscoin-api-backend/.
    ports:
      - 8000:3000
    volumes:
      - /var/uploads:/app/public/uploads
    restart: unless-stopped
    container_name: backend_container


  frontend_user:
    build: ./Vidscoin/.
    ports:
      - 3000:3000
    restart: unless-stopped
    container_name: frontend_user_container

  frontend_admin:
    build: ./vidscoin-react/.
    ports:
      - 5000:3000
    restart: unless-stopped
    container_name: frontend_admin_container

  nginx:
    build: ./custom-nginx/.
    ports:
      - 80:80
    volumes:
      - /home/dev2/custom-nginx/conf:/etc/nginx/conf.d
      - /var/vidscoin-react:/var/vidscoin-react
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend_user
      - backend
    restart: unless-stopped
    container_name: nginx_container
